Homework has been done.
Okkss/Homework pull request #1
Opened 2021-01-19 09:59 UTC by Okkss

2021-01-19 12:49 UTC, LiudmilaZhdanok requested changes
See notes

2021-01-19 12:49 UTC, LiudmilaZhdanok commented on homework/english/lecture1/grammar.md
> +1.	Your mum is working today?
It's a question, so "Is your mom working today"

2021-01-19 12:49 UTC, LiudmilaZhdanok commented on homework/english/lecture1/grammar.md
> +3.	Where is he to lives?
not "is". "Does" and without "s" at the end of verb. Where does he live?

2021-01-19 12:49 UTC, LiudmilaZhdanok commented on homework/english/lecture1/grammar.md
> +4.	Their mother cooks very well?
question construction

2021-01-19 12:49 UTC, zhdanok commented on homework/english/lecture1/grammar.md
> +5.	Lili is not rich, she is  not to drives a Mercedes.
"doesn't " without "to" and "s"

2021-01-19 12:49 UTC, zhdanok commented on homework/english/lecture1/grammar.md
> +10.	His wife having coffee at the moment?
question construction

2021-01-19 12:49 UTC, zhdanok commented on homework/english/lecture1/grammar.md
> +14.	My grandmother is not to work. She is on pension.
doesn't work

2021-01-19 12:49 UTC, LiudmilaZhdanok commented on homework/english/lecture1/grammar.md
> +16.	Where are you live?
do

2021-01-19 12:49 UTC, zhdanok commented on homework/english/lecture1/grammar.md
> +17.	Are You  play the piano well?
do. present simple

2021-01-19 12:49 UTC, LiudmilaZhdanok commented on homework/english/lecture1/grammar.md
> +22.	Maila is not to watch TV every morning.
does not watch

2021-01-19 12:49 UTC, LiudmilaZhdanok commented on homework/english/lecture1/grammar.md
> +10.	How are you like the game?
do

2021-01-19 12:54 UTC, LiudmilaZhdanok approved these changes
lgfm

2021-01-19 20:47 UTC, LiudmilaZhdanok approved these changes
lgfm

2021-01-19 20:48 UTC, LiudmilaZhdanok approved these changes
lgfm

2021-01-19 20:48 UTC, LiudmilaZhdanok approved these changes

2021-01-21 18:46 UTC, Okkss reviewed
lgfm

2021-01-21 18:46 UTC, merged